### ISSUE TITLE
Support Psalm 5.0

### ISSUE THREAD

**Issue by lptn** [psalm/psalm-plugin-phpunit#121]
It’s in beta now: https://github.com/vimeo/psalm/releases/tag/5.0.0-beta1

**Comment by someniatko** [comment]
@orklah I think it's only a problem of `composer.json` definition - this plugin already claims support for `dev-master`, so it's basically the same as claiming support of `^5@beta`.

**Comment by orklah** [comment]
Seems good. Mind providing a PR to allow 5.0?
