### ISSUE TITLE
`PossiblyUnusedMethod` for data providers

### ISSUE THREAD

**Issue by boesing** [psalm/psalm-plugin-phpunit#138]
Psalm with enabled PHPUnit plugin + enabled `findUnusedCode` reports data provider methods which are in use.

**Comment by orklah** [comment]
Yeah, this should be handled by this plugin indeed

**Comment by MidnightDesign** [comment]
It does work with `@dataProvider`, just not with the `PHPUnit\Framework\Attributes\DataProvider` attribute.

**Comment by boesing** [comment]
Hm, there was already an issue pointing to this problem in #131, will close here in favor of that issue.
