### ISSUE TITLE
 Data provider return type

### ISSUE THREAD

**Issue by whdigger** [psalm/psalm-plugin-phpunit#139]
Hi guys,
I have a phpunit test with data provider but I don't know how to fix this errors:

```
/**
 *
 * @psalm-type Cases = array<array-key, array>
 */
class JsonResponseTest extends TestCase
{
    /**
     * @dataProvider getCases
     * @param string $source
     * @param array $expect
     * @return void
     * @throws \JsonException
     */
    public function testResponse(string $source, array $expect): void
    {
        $response = new JsonResponse($source);
    }

    /**
     * @psalm-return Cases
     */
    public function getCases(): array
    {
        return [
            'null' => [null, 'null'],
            'empty' => ['', '""'],
            'number' => [1, '1'],
            'string' => ['1', '"1"'],
            'object' => [$object, '{"str":"value","int":1,"none":null}'],
            'array' => [$array, '{"str":"value","int":1,"none":null}'],
        ];
    }
}
```

The error I am getting
```
ERROR: PossiblyInvalidArgument - src/Http/Test/JsonResponseTest.php:570:21 - Argument 1 of App\Http\Test\JsonResponseTest::testResponse expects string, mixed provided by App\Http\Test\JsonResponseTest::getcases():(array<array-key, array<array-key, mixed>>) (see https://psalm.dev/092)
    public function testResponse(string $source, array $expect): void


ERROR: PossiblyInvalidArgument - src/Http/Test/JsonResponseTest.php:570:21 - Argument 2 of App\Http\Test\JsonResponseTest::testResponse expects array<array-key, mixed>, mixed provided by App\Http\Test\JsonResponseTest::getcases():(array<array-key, array<array-key, mixed>>) (see https://psalm.dev/092)
    public function testResponse(string $source, array $expect): void
```

**Comment by weirdan** [comment]
To start with, your data provider as it is now won't work with PHPUnit. Data providers need to return an iterable (array would work, too) where each element is an array containing parameters for the test method and thus must match the test method signature. Your signature is `string, array`, so your data provider needs to return something like this:

```php
return [
 // string,  array 
  [ 'null',  [null, 'null'] ],
  [ 'empty,  ['', '""']     ]
  // and so on
];
```

And then you will need to make Psalm aware of what you return:

```php
/**
 * @return list<array{string, array}>
 */
public function getCases(): array 
{
    return [
      // string,  array 
      [  'null',  [null, 'null'] ],
      [  'empty,  ['', '""']     ]
      // and so on
    ];
}
```
You probably want to specify further what that array passed to `$expected` looks like as well.

Or, if that `array $expected` should have actually been a string and `string $source` should have been mixed, you may keep the returned value as is, and just make sure your docblock matches it:

```php
/** @return array<string, array{mixed, string}> */
```

**Comment by whdigger** [comment]
Yes it was a mistake, thanks for help. Tell me pls where i can read about the description of return types for psalm and what is difference between the signs < and { for doc block?

**Comment by whdigger** [comment]
If I want to display a set in which an error was made in php-unit, how can I describe the set then?
For example, for such a set
```
        return [
            'null' => [null, '1'],
        ];
```
This case was a bug with the message `JsonResponseTest::testResponse with data set "**null**" (null, '1')`

**Comment by weirdan** [comment]
That would be `array<string, array{mixed, string}>`.

> Tell me pls where i can read about the description of return types for psalm and what is difference between the signs < and { for doc block?

You can start here: https://psalm.dev/docs/annotating_code/type_syntax/atomic_types/

For array types specifically, there's a dedicated chapter here: https://psalm.dev/docs/annotating_code/type_syntax/array_types/
