### ISSUE TITLE
why `packageVersionIs` method exists?

### ISSUE THREAD

**Issue by vladyslavstartsev** [psalm/psalm-plugin-phpunit#76]
I have not found usages of this `private` method
https://github.com/psalm/psalm-plugin-phpunit/blob/83b5c107a8902c6c7f0b4467685eac16b3f932b4/src/Plugin.php#L28-L38

May be it needs to be deleted?
Also if deleting this, also delete `composer/semver` dependency `composer remove composer/semver` because it's used only there

**Comment by weirdan** [comment]
It used to be used to check for PHPUnit version. Semver, though, is used in tests, so it cannot be removed, but should instead be demoted to dev dependency.

**Comment by weirdan** [comment]
PRs are welcome ;)
