### ISSUE TITLE
Data provider return type

### ISSUE THREAD

**Issue by matiux** [psalm/psalm-plugin-phpunit#78]
I have a phpunit test with data provider but I can't understand how to fix this errors:

`MismatchingDocblockReturnType` **1**

`MixedInferredReturnType` **2**

`PossiblyInvalidArgument` **3**

```
class MyTest extends TestCase
{
  
    /**
     * @psalm-return list<array-key, array<array-key, mixed>> **1** **2**
     */
    public function dataProvider(): array
    {
        return [
            [      [],   "message...'"    ],
            [    ['invalid' => true],    "message" ],
            [    ['foo' => 'value'],      "message" ],
        ];
    }

    /**
     * @test
     * @dataProvider dataProvider
     */
    public function my_test(array $payload, string $errorMessage): void **3**
    {
       
    }
}

```

**Comment by weirdan** [comment]
This should do (although you may want to provide more detailed type for `$payload` in both places):
```php
    /**
     * @psalm-return list<array-key, array{array,string}>
     */
    public function dataProvider(): array
```

Providers return iterables of argument tuples, each of those tuples are going to be used as arguments to the test referencing the provider. So the plugin checks that the types of those are compatible.

**Comment by matiux** [comment]
@weirdan I have solved with

```
    /**
     * @psalm-return list<array{array,string}>
     */
```
