### ISSUE TITLE
MissingDependency in phpunit dependencies

### ISSUE THREAD

**Issue by marceloaas** [psalm/psalm-plugin-phpunit#80]
The following error occours:

```bash
ERROR: MissingDependency - tests/myTest.php - PHPUnit\Framework\MockObject\Builder\InvocationMocker depends on class or interface phpunit\framework\mockobject\builder\parametersmatch that does not exist (see https://psalm.dev/157)
        $aMock->expects($this->never())
```

The components from error
```
vendor/phpunit/phpunit/src/Framework/MockObject/Builder/
├── Identity.php
├── InvocationMocker.php
├── InvocationStubber.php
├── Match.php
├── MethodNameMatch.php
├── ParametersMatch.php
└── Stub.php

0 directories, 7 files
```
Psalm.xml config

```xml
    <projectFiles>
        <directory name="src"/>
        <directory name="tests"/>
        <ignoreFiles>
            <directory name="vendor"/>
        </ignoreFiles>
    </projectFiles>
    <plugins>
        <pluginClass class="Psalm\PhpUnitPlugin\Plugin"/>
    </plugins>
```

### Info
- Psalm version: `Psalm 3.12.2@7c7ebd068f8acaba211d4a2c707c4ba90874fa26`
- PHPUnit version: `"phpunit/phpunit": "^9.1.4"`
- PHPUnit plugin psalm: `"psalm/plugin-phpunit": "^0.10.1"`

**Comment by weirdan** [comment]
Does it happen if you downgrade `nikic/php-parser` to 4.6?

**Comment by marceloaas** [comment]
@weirdan 

after downgrade/update, checked:

- `nikic/php-parser: 4.4` - works fine
- `nikic/php-parser: 4.6` - works fine
- `nikic/php-parser: 4.7` - The problem related in this thread

**Comment by marceloaas** [comment]
The following related issues:

- https://github.com/nikic/PHP-Parser/issues/690
- https://github.com/nikic/PHP-Parser/pull/672#issuecomment-659343331
